name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 10 * * 6'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
    - uses: coursier/cache-action@v6
    - run: sbt -v scalafmtSbtCheck scalafmtCheckAll "+test"
